DROP USER IF EXISTS 'rrhh_user';
CREATE USER 'rrhh_user';
GRANT CREATE USER ON *.* TO 'rrhh_user';

DROP USER IF EXISTS 'analytic_user';
CREATE USER 'analytic_user';
GRANT SELECT,CREATE VIEW,SHOW VIEW ON F1_OLAP.* TO 'analytic_user';

DROP USER IF EXISTS 'manager_user';
CREATE USER 'manager_user';
GRANT UPDATE,INSERT,DELETE,DROP,EVENT,TRIGGER ON F1_OLAP.* TO 'manager_user';
GRANT UPDATE,INSERT,DELETE,DROP,EVENT,TRIGGER ON F1_OLTP.* TO 'manager_user';